language: cpp


matrix:
  include:
    - os: linux
      dist: bionic
      env: OFBUILD_TRAVIS_BUILDTYPE=debug
    - os: linux
      dist: bionic
      env: OFBUILD_TRAVIS_BUILDTYPE=release
    - os: osx
      osx_image: xcode11.1
      env: OFBUILD_TRAVIS_BUILDTYPE=release


notifications:
  email:
    on_success: always
    on_failure: always


addons:
  apt:
    packages:
    - cmake
    - git
    - gcc
    - g++
    - gfortran
    - libboost-dev
    - libboost-test-dev
    - qt5-default
    - qtbase5-dev
    - qtbase5-dev-tools
    - qttools5-dev
    - qttools5-dev-tools
    - libqt5svg5-dev
    - libgdal-dev
    - libgeos++-dev
    - rapidjson-dev
    - p7zip-full 
    - gnuplot 
    - graphviz
  homebrew:
    packages:
    - boost
    - rapidjson
    - gdal
    - geos
    - qt5
    - doxygen
    - p7zip
    - gnuplot
    - cmake
    update: true

#####################################################


install:
  - |
    if [ "${TRAVIS_OS_NAME}" == "osx" ]
    then
      export PATH=$PATH:$(brew --prefix qt5)/bin
    fi


before_script:
  - echo "SET(OPENFLUID_ENABLE_MARKET 1)" > CMake.in.local.cmake
  - echo "SET(OFBUILD_TESTS_ENABLE_FORTRAN 1)" >> CMake.in.local.cmake  
  - echo "SET(OFBUILD_UNITTESTS_RUN_OPTIONS \"--log_level=all\")" >> CMake.in.local.cmake
  - mkdir _build
  - cd _build
  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ]
    then
      if [ "${OFBUILD_TRAVIS_BUILDTYPE}" == "debug" ]
      then 
        cmake .. -DOPENFLUID_ENABLE_HEAVYTESTING=1
      elif [ "${OFBUILD_TRAVIS_BUILDTYPE}" == "release" ]
      then
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
      fi
    elif [ "${TRAVIS_OS_NAME}" == "osx" ]
    then 
      cmake .. -DCMAKE_PREFIX_PATH=$(brew --prefix qt5)/lib/cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local 
    fi  
 
 
script:
  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ]
    then
      if [ "${OFBUILD_TRAVIS_BUILDTYPE}" == "debug" ]
      then 
        make && ctest --output-on-failure
      elif [ "${OFBUILD_TRAVIS_BUILDTYPE}" == "release" ]
      then 
        make stylecheck && make && cpack
      fi
    elif [ "${TRAVIS_OS_NAME}" == "osx" ]
    then 
      make && cmake -P ofpack-osx-brewcask.cmake
    fi
